### ISSUE TITLE
milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [data301-2020-winter1/course-project-solo_113#1]
Hi,

I think you didn't commit your changes to the repository that's why I didn't see your work for milestone 2.

Good job:

few feedbacks:

- [x] you should extract your method chained code and put in in a separate python script and import it in your python notebook

- [x] in your bar charts you should sort the result 

- [x] it is good if you also consider analyzing total number of deaths over the years
